apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: http
      protocol: TCP
      port: 15673
      targetPort: 15673
    - name: amqp
      protocol: TCP
      port: 5673
      targetPort: 5673

